#추후에 메인서버 배포시에는 작성 예정
name: Main Server Merge
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.   # Repo checkout
        uses: actions/checkout@v3

      - name: Set application.properties from secrets
        run: |
          echo "${{ secrets.MAIN_APPLICATION_PROPERTIES }}" > src/main/resources/application.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: remove plain.jar
        run: rm -rf build/libs/*plain.jar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/bossvery-back:latest

      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.MAIN_HOST }}
          username: ${{ secrets.MAIN_USERNAME }}
          key: ${{ secrets.MAIN_SSH_KEY }}
          port: ${{ secrets.TEST_PORT }}
          
          timeout: 40s  # 30초 기본
          script: |
            docker image pull ghcr.io/readyvery/bossvery-back:latest
            cd docker
            docker-compose stop bossvery || true
            docker-compose rm -f bossvery || true
            docker-compose up -d bossvery
